name: Docker image

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: koen20
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./amd64.dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/koen20/recorder:amd64
      - name: Build and push arm32v7
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./arm32v7.dockerfile
          platforms: linux/arm/v7
          push: true
          tags: ghcr.io/koen20/recorder:arm32v7
      - name: latest manifest
        run: ./hooks/post_push